// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_fly
global.__objectDepths[1] = 0; // obj_FlyGameEngine
global.__objectDepths[2] = 0; // obj_flyswatter
global.__objectDepths[3] = 0; // obj_mouse
global.__objectDepths[4] = 0; // obj_arrowkeydown
global.__objectDepths[5] = 0; // ArrowKeyGameEngine
global.__objectDepths[6] = 0; // obj_enemybullet
global.__objectDepths[7] = 0; // obj_akey
global.__objectDepths[8] = 0; // obj_skey
global.__objectDepths[9] = 0; // obj_arrowkeyleft
global.__objectDepths[10] = 0; // obj_arrowkeyup
global.__objectDepths[11] = 0; // obj_dkey
global.__objectDepths[12] = 0; // obj_CircleGameEngine
global.__objectDepths[13] = 0; // obj_circle
global.__objectDepths[14] = 0; // obj_ShooterGameEnemy
global.__objectDepths[15] = 0; // obj_ArrowKeyGameplay
global.__objectDepths[16] = 0; // obj_arrowkeyright
global.__objectDepths[17] = 0; // obj_player
global.__objectDepths[18] = 0; // obj_solidwall
global.__objectDepths[19] = 0; // obj_redbox
global.__objectDepths[20] = -10; // obj_light
global.__objectDepths[21] = 0; // obj_DarkGameEngine
global.__objectDepths[22] = 0; // obj_RaceGameEngine
global.__objectDepths[23] = -11; // obj_racegamebargreen
global.__objectDepths[24] = -20; // obj_racegameslider
global.__objectDepths[25] = 0; // obj_racegamebarred
global.__objectDepths[26] = 0; // obj_hordeenemy
global.__objectDepths[27] = 0; // obj_hordeplayer
global.__objectDepths[28] = 0; // obj_car
global.__objectDepths[29] = 0; // obj_greenbox
global.__objectDepths[30] = 0; // obj_SpellingGameEngine
global.__objectDepths[31] = 0; // obj_invisiblewall
global.__objectDepths[32] = 0; // obj_hordebullet
global.__objectDepths[33] = 0; // obj_mazeplayer
global.__objectDepths[34] = 0; // obj_mazeexit
global.__objectDepths[35] = 0; // obj_wkey
global.__objectDepths[36] = 0; // obj_HordeGameEngine
global.__objectDepths[37] = 0; // obj_transitionengine
global.__objectDepths[38] = 0; // obj_MazeGameEngine
global.__objectDepths[39] = 0; // obj_Title
global.__objectDepths[40] = 0; // obj_randomizer
global.__objectDepths[41] = -11; // obj_GameTimer
global.__objectDepths[42] = 0; // obj_wasdalert
global.__objectDepths[43] = 0; // obj_CancelReset
global.__objectDepths[44] = 0; // obj_heart
global.__objectDepths[45] = 0; // obj_AlwaysThere
global.__objectDepths[46] = 0; // obj_spellingalert
global.__objectDepths[47] = 0; // obj_resultsdraw
global.__objectDepths[48] = 0; // obj_pausemenudraw
global.__objectDepths[49] = 0; // obj_mousealert
global.__objectDepths[50] = 0; // obj_spacealert
global.__objectDepths[51] = 0; // obj_GameTimerWin
global.__objectDepths[52] = -100; // obj_Instructions
global.__objectDepths[53] = 0; // obj_gradbackground
global.__objectDepths[54] = 0; // obj_CleanGameEnginedifficulty
global.__objectDepths[55] = 0; // obj_CleanGameEnginemenu
global.__objectDepths[56] = 0; // obj_mazewall
global.__objectDepths[57] = 0; // obj_CleanGameEnginegameselect
global.__objectDepths[58] = 0; // obj_SetVariablesOnce
global.__objectDepths[59] = 0; // obj_setWASDoption
global.__objectDepths[60] = 0; // obj_SoundMaster
global.__objectDepths[61] = 0; // FORGIFSOBJ
global.__objectDepths[62] = 0; // obj_hard
global.__objectDepths[63] = 0; // obj_normal
global.__objectDepths[64] = 0; // obj_racegameselect
global.__objectDepths[65] = 0; // obj_easy
global.__objectDepths[66] = 0; // obj_back
global.__objectDepths[67] = 0; // obj_optionsmenu
global.__objectDepths[68] = 0; // obj_flygameselect
global.__objectDepths[69] = 0; // obj_darkgameselect
global.__objectDepths[70] = 0; // obj_dodgegameselect


global.__objectNames[0] = "obj_fly";
global.__objectNames[1] = "obj_FlyGameEngine";
global.__objectNames[2] = "obj_flyswatter";
global.__objectNames[3] = "obj_mouse";
global.__objectNames[4] = "obj_arrowkeydown";
global.__objectNames[5] = "ArrowKeyGameEngine";
global.__objectNames[6] = "obj_enemybullet";
global.__objectNames[7] = "obj_akey";
global.__objectNames[8] = "obj_skey";
global.__objectNames[9] = "obj_arrowkeyleft";
global.__objectNames[10] = "obj_arrowkeyup";
global.__objectNames[11] = "obj_dkey";
global.__objectNames[12] = "obj_CircleGameEngine";
global.__objectNames[13] = "obj_circle";
global.__objectNames[14] = "obj_ShooterGameEnemy";
global.__objectNames[15] = "obj_ArrowKeyGameplay";
global.__objectNames[16] = "obj_arrowkeyright";
global.__objectNames[17] = "obj_player";
global.__objectNames[18] = "obj_solidwall";
global.__objectNames[19] = "obj_redbox";
global.__objectNames[20] = "obj_light";
global.__objectNames[21] = "obj_DarkGameEngine";
global.__objectNames[22] = "obj_RaceGameEngine";
global.__objectNames[23] = "obj_racegamebargreen";
global.__objectNames[24] = "obj_racegameslider";
global.__objectNames[25] = "obj_racegamebarred";
global.__objectNames[26] = "obj_hordeenemy";
global.__objectNames[27] = "obj_hordeplayer";
global.__objectNames[28] = "obj_car";
global.__objectNames[29] = "obj_greenbox";
global.__objectNames[30] = "obj_SpellingGameEngine";
global.__objectNames[31] = "obj_invisiblewall";
global.__objectNames[32] = "obj_hordebullet";
global.__objectNames[33] = "obj_mazeplayer";
global.__objectNames[34] = "obj_mazeexit";
global.__objectNames[35] = "obj_wkey";
global.__objectNames[36] = "obj_HordeGameEngine";
global.__objectNames[37] = "obj_transitionengine";
global.__objectNames[38] = "obj_MazeGameEngine";
global.__objectNames[39] = "obj_Title";
global.__objectNames[40] = "obj_randomizer";
global.__objectNames[41] = "obj_GameTimer";
global.__objectNames[42] = "obj_wasdalert";
global.__objectNames[43] = "obj_CancelReset";
global.__objectNames[44] = "obj_heart";
global.__objectNames[45] = "obj_AlwaysThere";
global.__objectNames[46] = "obj_spellingalert";
global.__objectNames[47] = "obj_resultsdraw";
global.__objectNames[48] = "obj_pausemenudraw";
global.__objectNames[49] = "obj_mousealert";
global.__objectNames[50] = "obj_spacealert";
global.__objectNames[51] = "obj_GameTimerWin";
global.__objectNames[52] = "obj_Instructions";
global.__objectNames[53] = "obj_gradbackground";
global.__objectNames[54] = "obj_CleanGameEnginedifficulty";
global.__objectNames[55] = "obj_CleanGameEnginemenu";
global.__objectNames[56] = "obj_mazewall";
global.__objectNames[57] = "obj_CleanGameEnginegameselect";
global.__objectNames[58] = "obj_SetVariablesOnce";
global.__objectNames[59] = "obj_setWASDoption";
global.__objectNames[60] = "obj_SoundMaster";
global.__objectNames[61] = "FORGIFSOBJ";
global.__objectNames[62] = "obj_hard";
global.__objectNames[63] = "obj_normal";
global.__objectNames[64] = "obj_racegameselect";
global.__objectNames[65] = "obj_easy";
global.__objectNames[66] = "obj_back";
global.__objectNames[67] = "obj_optionsmenu";
global.__objectNames[68] = "obj_flygameselect";
global.__objectNames[69] = "obj_darkgameselect";
global.__objectNames[70] = "obj_dodgegameselect";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for